In [19]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

In [1]:
import sklearn

In [3]:
Dubai_Properties = pd.read_csv('House_Price_Regression.csv')

In [4]:
Dubai_Properties

,neighborhood_recode,latitude,longitude,price,no_of_bedrooms,no_of_bathrooms,quality_recode,maid_room_recode,unfurnished_recode,balcony_recode,...,private_garden_recode,private_gym_recode,private_jacuzzi_recode,private_pool_recode,security_recode,shared_gym_recode,shared_pool_recode,shared_spa_recode,view_of_water_recode,size_in_m_2
0,46.0,25.113208,55.138932,2700000,1,2,2.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,100.242337
1,46.0,25.106809,55.151201,2850000,2,2,2.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,146.972546
2,36.0,25.063302,55.137728,1150000,3,5,2.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,181.253753
3,11.0,25.227295,55.341761,2850000,2,3,1.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,187.664060
4,46.0,25.114275,55.139764,1729200,0,1,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,47.101821
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1900,42.0,25.176892,55.310712,1500000,2,2,3.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,100.985561
1901,42.0,25.166145,55.276684,1230000,1,2,2.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,70.606280
1902,16.0,25.206500,55.345056,2900000,3,5,2.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,179.302790
1903,37.0,25.073858,55.229844,675000,1,2,2.0,0.0,1.0,1.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,68.748220
1904,36.0,25.079130,55.154713,760887,1,2,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,74.322400

In [7]:
X = Dubai_Properties.loc[:, ['latitude', 'longitude', 'no_of_bedrooms', 'no_of_bathrooms', 'quality_recode', 'private_garden_recode', 'private_pool_recode', 'private_jacuzzi_recode', 'private_gym_recode']]
Y = Dubai_Properties['price']

In [15]:
class RandomSimpleValidation : 
    # D --> have to be a pandas data frame.
    # k --> is the proportion of observation of D that define D_train.
    # response --> have to be a string with the name of the response variable.
    # model --> object containing the initialized model to use.
    # The function has been created thinking that the model to be used will be one from the `sklearn` library.
    # metric --> It's the name of the validation metric.
    # random_seed --> seed to replicate the random process.
        
    def __init__(self, k, metric, model, random_seed):
        self.k = k
        self.metric = metric
        self.model = model
        self.random_seed = random_seed   

    def fit(self, D, response_name):         
        N = len(D)
        self.D_train = D.sample(frac=self.k, replace=False, random_state=self.random_seed)
        self.D_test = D.drop( self.D_train.index , )
        self.X_train = self.D_train.loc[: , self.D_train.columns != response_name]
        self.Y_train = self.D_train.loc[: , response_name]
        self.X_test = self.D_test.loc[: , self.D_test.columns != response_name]
        self.Y_test = self.D_test.loc[: , response_name]
        self.model.fit(self.X_train, self.Y_train)
    
    def predict(self):
        self.Y_predict_test = self.model.predict(self.X_test)
    
    def compute_metric(self):    
        if self.metric == 'MSE':
            self.ECM_test = np.mean((self.Y_predict_test - self.Y_test) ** 2)
            return self.ECM_test
        elif self.metric == 'Accuracy':
            self.TAC_test = np.mean((self.Y_predict_test == self.Y_test))
            return self.TAC_test

In [20]:
LinearRegression_Model = LinearRegression()
KNN_Model = KNeighborsRegressor(n_neighbors=10,  p=2, metric='minkowski')

In [18]:
RandomSimpleValidation_init = RandomSimpleValidation(k=0.75, metric='ECM', model=LinearRegression_Model, random_seed=123)

RandomSimpleValidation_init.fit(D=Dubai_Properties, response_name='price')

RandomSimpleValidation_init.predict()

ECM_test_Random_Simple_Validation  = RandomSimpleValidation_init.compute_metric()

ECM_test_Random_Simple_Validation

2202429450423.991

In [21]:
RandomSimpleValidation_init = RandomSimpleValidation(k=0.75, metric='ECM', model=KNN_Model, random_seed=123)

RandomSimpleValidation_init.fit(D=Dubai_Properties, response_name='price')

RandomSimpleValidation_init.predict()

ECM_test_Random_Simple_Validation  = RandomSimpleValidation_init.compute_metric()

ECM_test_Random_Simple_Validation

2451629828197.658

In [11]:
Y_pred = model.predict(X)

In [12]:
MSE = np.sum(Y-Y_pred)**2
MSE

3.4196667719754714e-10